sonar.projectKey=Bahmni_bahmni-module-immunization
sonar.organization=bahmni
sonar.projectName=bahmni-module-immunization

sonar.sources=api/src/main/java
sonar.tests=api/src/test/java
sonar.java.binaries=api/target/classes

sonar.coverage.jacoco.xmlReportPaths=api/target/jacoco-reports/jacoco.xml

sonar.coverage.exclusions=**/ImmunizationModuleActivator.java

sonar.sourceEncoding=UTF-8